version: '3.2'
services:
  #for passing messages
  rabbit_broker:
    image: rabbitmq:3-management-alpine
    ports: 
     - 5672:5672
  #sets up the channels on the exchange I suppose
  exchange-setup:
    build: local_dragonfly/ 
    volumes:
      - type: bind
        source: "./local_dragonfly/project8_authentications.json"
        target: "/root/.project8_authentications.json"
      - type: bind
        source: "./local_dragonfly/custom_homeputer_dragonfly"
        target: "/custom_homeputer_dragonfly"
    command: ["dragonfly", "monitor", "-vv", "-b", "rabbit_broker", "-e", "alerts"]
    depends_on:
      - rabbit_broker
  pm25:
    build: local_dragonfly/ 
    volumes:
      - type: bind
        source: "./local_dragonfly/project8_authentications.json"
        target: "/root/.project8_authentications.json"
      - type: bind
        source: "./local_dragonfly/custom_homeputer_dragonfly"
        target: "/custom_homeputer_dragonfly"
    devices:
      - "/dev/ttyS0:/dev/ttyS0"
    #command: ["dragonfly", "serve", "-c", "/custom_homeputer_dragonfly/pm25.yaml","-b", "rabbit_broker","-vv"]
    command: ["dragonfly", "serve", "-c", "/custom_homeputer_dragonfly/pm25.yaml","-b", "10.0.0.3","-vv"]
    #depends_on:
    #  - rabbit_broker
