version: "3"
services:
  pm25_monitor:
    build: .
    volumes:
      - .:/app
    devices:
      - /dev/ttyS0:/dev/ttyS0
    container_name: pm25_monitor
    working_dir: /app
    command: ['python','pm25_monitor.py']
